# Generated by Django 3.0.10 on 2020-11-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20201115_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountchoice',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
