name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          script_stop: true
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd musician_tips
            git pull --rebase
            docker-compose -f production.yml build
            supervisorctl restart musician_tips
