# Generated by Django 3.0.10 on 2020-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201113_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='landing_text',
            field=models.CharField(blank=True, default='Thank you for listening. Gracias por su atención.', max_length=140),
        ),
    ]
