# Generated by Django 3.0.10 on 2020-11-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_stripe_enabled',
            new_name='has_stripe_enabled',
        ),
    ]
